### ISSUE TITLE
High memory usage/leak

### ISSUE THREAD

**Issue by vinc817** [nylonee/watchlistarr#174]
This process is taking over 20% of the RAM:
/usr/local/openjdk-11/bin/java -Dsonarr.apikey=*apikey* -Dsonarr.baseUrl=http://192.168.2.150:8989/ -Dsonarr.qualityProfile=WEB-DL1080p -Dradarr.api *can't read the rest of the process*

Killing Watchlistarr (on Unraid) fixed it.

![image](https://github.com/nylonee/watchlistarr/assets/34588704/b12ca0c8-1482-41ee-b552-e08f32372a28)

**Comment by nylonee** [comment]
The -Xmx100 argument would indeed help, but your top is still worrying. I'll keep this thread open so that I can try this out myself when I'm back at a computer (I'll been afk for a while, perhaps until October)

**Comment by paulbaird87** [comment]
Same, Unraid reporting container using 3.2gb dedotated wam

**Comment by danimal1986** [comment]
seems like the update may have fixed it?

**Comment by vinc817** [comment]
> seems like the update may have fixed it?

It hasn't fixed mine unfortunately. Still using lots of RAM.

**Comment by nylonee** [comment]
Thanks all for your comments, the latest build wouldn't have fixed this issue, as this looks like a real memory leak.

Out of curiosity, is everybody here who's getting the issue running on a java version that's less than version 21? (If you're running via docker, then the answer is yes I'm using version 11).

**Comment by danimal1986** [comment]
> Thanks all for your comments, the latest build wouldn't have fixed this issue, as this looks like a real memory leak.
> 
> Out of curiosity, is everybody here who's getting the issue running on a java version that's less than version 21? (If you're running via docker, then the answer is yes I'm using version 11).

Docker, but no idea what Java version

**Comment by adamtiley** [comment]
Also getting this issue - 4GB's of ram taken up. I've turned it off for now.

**Comment by Starminder** [comment]
Windows.

Exception in thread "io-compute-0" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1252)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1300)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at scala.util.Right.toString(Either.scala:471)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
        at http.HttpClient.$anonfun$makeHttpRequest$7(HttpClient.scala:72)
        at http.HttpClient$$Lambda$406/0x0000000100444040.apply(Unknown Source)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1171)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:240)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1358)
        at cats.effect.IOFiber.run(IOFiber.scala:113)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:721)
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)

**Comment by DHernan** [comment]
Same issue here. Good to know the memory limit command and I’ll check it out later. I’m using Docker for windows

**Comment by m33ts4k0z** [comment]
Hi.

Same for me on Unraid. The RAM usage is constantly at 3GB

**Comment by rustyserpent** [comment]
This is Still an issue with docker on Unraid.

**Comment by m33ts4k0z** [comment]
For all of you experiencing this on Unraid, adding this flag in the extra parameters field of the container will solve the issue: `--memory=1G`

It is now using about 400MB for over 2 weeks.

**Comment by bayramog** [comment]
Same issue at Unraid again. Limiting memory is only solution for now.

<img width="393" alt="Image" src="https://github.com/user-attachments/assets/d4850f1d-829e-4ffb-b97a-e3b73f1a10b6" />

**Comment by paulbaird87** [comment]
Update.... Installed on Docker (Unraid). Been running for an hour and up to 2.8gb

**Comment by vinc817** [comment]
@Orthynon Same for me. I have now switched to Pulsarr.
