### ISSUE TITLE
Docker Compose missing config file

### ISSUE THREAD

**Issue by kymocode** [nylonee/watchlistarr#176]
Anyone getting the following with docker compose up

```
[+] Running 1/0
 ✔ Container watchlistarr-watchlistarr-1  Created                                                                                                                                                                                       0.0s
Attaching to watchlistarr-watchlistarr-1
watchlistarr-watchlistarr-1  | 03:02:04.001 [io-compute-35] ERROR configuration.ConfigurationUtils$ - Unable to connect to Sonarr at host.docker.internal:8989, with error java.net.ConnectException: Connection refused
watchlistarr-watchlistarr-1  | java.lang.IllegalArgumentException: Unable to connect to Sonarr at host.docker.internal:8989, with error java.net.ConnectException: Connection refused
watchlistarr-watchlistarr-1  |  at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:336)
watchlistarr-watchlistarr-1  |  at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$5(ConfigurationUtils.scala:132)
watchlistarr-watchlistarr-1  |  at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-watchlistarr-1  |  at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-watchlistarr-1  |
watchlistarr-watchlistarr-1  |
watchlistarr-watchlistarr-1  |  at map @ configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$4(ConfigurationUtils.scala:126)
watchlistarr-watchlistarr-1  |  at flatMap @ configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$4(ConfigurationUtils.scala:126)
watchlistarr-watchlistarr-1  |  at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-watchlistarr-1  |  at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)

```

Your config file is located here 

`/var/snap/docker/common/var-lib-docker/volumes/watchlistarr_config/_data/config.yaml`

Can this be automatically created next to the docker-compose.yml file?

**Comment by nylonee** [comment]
Could you share the docker-compose file you're using to start up Watchlistarr?

**Comment by waibashi** [comment]
I have exactly the same issue creating my docker-compose. Here is mine

`version: '3.8'
services:
  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    environment:
      SONARR_API_KEY:  _Key Removed_
      RADARR_API_KEY: _Key Removed_
      PLEX_TOKEN:  _Token Removed_
    volumes:
      - ./config:/app/config`

`root@docker:/docker/watchlistarr# docker-compose logs -f
Attaching to watchlistarr
watchlistarr    | 03:26:13.973 [io-compute-1] ERROR configuration.ConfigurationUtils$ - Unable to connect to Sonarr at host.docker.internal:8989, with error java.net.ConnectException: Connection refused
watchlistarr    | java.lang.IllegalArgumentException: Unable to connect to Sonarr at host.docker.internal:8989, with error java.net.ConnectException: Connection refused
watchlistarr    |       at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:336)
watchlistarr    |       at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$5(ConfigurationUtils.scala:132)
watchlistarr    |       at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr    |       at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr    |       at map @ configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$4(ConfigurationUtils.scala:126)
watchlistarr    |       at flatMap @ configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$4(ConfigurationUtils.scala:126)
watchlistarr    |       at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr    |       at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr exited with code 1`

Yet, my docker LXC can ping my Sonarr LXC and I have communication between both of them.

**Comment by kymocode** [comment]
> Could you share the docker-compose file you're using to start up Watchlistarr?

My apologies I did not see your reply. Config file: 

`version: '3.8'
services:
  watchlistarr:
    image: nylonee/watchlistarr
    environment:
      SONARR_API_KEY: d980d263cfae406b8857e0b898aa74f2
      RADARR_API_KEY: 0e3d0df37dba40c3a5e3b1d8437b8572
      PLEX_TOKEN: VWEsp3VsRH8uyBnzmmdz
    volumes:
      - config:/app/config
    restart: unless-stopped

volumes:
  config:
`
