### ISSUE TITLE
plex token no longer working

### ISSUE THREAD

**Issue by phynias** [nylonee/watchlistarr#177]
noticed my watchlistarr container restarting in a loop and checked  logs:

```
14:39:34.065 [io-compute-12] WARN  configuration.ConfigurationUtils$ - Unable to generate an RSS feed: org.http4s.client.UnexpectedStatus: unexpected HTTP status: 401 Unauthorized for request POST https://discover.provider.plex.tv/rss?X-Plex-Token=TTktYgQLzEuzv3y2J11y&X-Plex-Client-Identifier=watchlistarr
.....

14:40:47.999 [io-compute-6] INFO  PingTokenSync$ - Pinged plex.tv to update access token expiry
Exception in thread "io-compute-15" java.lang.OutOfMemoryError: Java heap space
        at org.typelevel.jawn.AsyncParser.resizeIfNecessary(AsyncParser.scala:177)
        at org.typelevel.jawn.AsyncParser.absorb(AsyncParser.scala:137)
        at org.typelevel.jawn.fs2.Absorbable$$anon$4.absorb(Absorbable.scala:53)
        at org.typelevel.jawn.fs2.Absorbable$$anon$4.absorb(Absorbable.scala:50)
        at org.typelevel.jawn.fs2.package$.$anonfun$parseJson$3(package.scala:46)
        at org.typelevel.jawn.fs2.package$$$Lambda$1090/0x00000008406fe040.apply(Unknown Source)
        at fs2.Pull$$anon$1.cont(Pull.scala:149)
        at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:748)
        at fs2.Pull$BindBind.cont(Pull.scala:735)
        at fs2.Pull$ContP.apply(Pull.scala:683)
        at fs2.Pull$ContP.apply$(Pull.scala:683)
        at fs2.Pull$Bind.apply(Pull.scala:691)
        at fs2.Pull$Bind.apply(Pull.scala:691)
        at fs2.Pull$UnconsRunR$1.$anonfun$out$2(Pull.scala:1019)
        at fs2.Pull$UnconsRunR$1$$Lambda$924/0x0000000840640840.apply(Unknown Source)
        at fs2.Pull$.$anonfun$compile$2(Pull.scala:952)
        at fs2.Pull$$$Lambda$908/0x0000000840632840.apply(Unknown Source)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1190)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:264)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1358)
        at cats.effect.IOFiber.run(IOFiber.scala:113)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:721)
java.lang.OutOfMemoryError: Java heap space
        at org.typelevel.jawn.AsyncParser.resizeIfNecessary(AsyncParser.scala:177)
        at org.typelevel.jawn.AsyncParser.absorb(AsyncParser.scala:137)
        at org.typelevel.jawn.fs2.Absorbable$$anon$4.absorb(Absorbable.scala:53)
        at org.typelevel.jawn.fs2.Absorbable$$anon$4.absorb(Absorbable.scala:50)
        at org.typelevel.jawn.fs2.package$.$anonfun$parseJson$3(package.scala:46)
        at org.typelevel.jawn.fs2.package$$$Lambda$1090/0x00000008406fe040.apply(Unknown Source)
        at fs2.Pull$$anon$1.cont(Pull.scala:149)
        at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:748)
        at fs2.Pull$BindBind.cont(Pull.scala:735)
        at fs2.Pull$ContP.apply(Pull.scala:683)
        at fs2.Pull$ContP.apply$(Pull.scala:683)
        at fs2.Pull$Bind.apply(Pull.scala:691)
        at fs2.Pull$Bind.apply(Pull.scala:691)
        at fs2.Pull$UnconsRunR$1.$anonfun$out$2(Pull.scala:1019)
        at fs2.Pull$UnconsRunR$1$$Lambda$924/0x0000000840640840.apply(Unknown Source)
        at fs2.Pull$.$anonfun$compile$2(Pull.scala:952)
        at fs2.Pull$$$Lambda$908/0x0000000840632840.apply(Unknown Source)
        at cats.effect.IOFiber.succeeded(IOFiber.scala:1190)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:264)
        at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1358)
        at cats.effect.IOFiber.run(IOFiber.scala:113)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:721)


```
i tried to grab a new token and still same thing.

**Comment by nylonee** [comment]
Heya, this isn't a token issue, your app is running out of memory. I'd check how much RAM you have on what you're running this on, and possibly you're being a bit too aggressive with the memory settings. How are you starting up Watchlistarr?
