### ISSUE TITLE
Unable to connect to Sonar or generate config file.

### ISSUE THREAD

**Issue by Redryan243** [nylonee/watchlistarr#181]
I have tried with a few different configs, however I am consistently getting this error

`[+] Running 1/0
 ✔ Container jarvis-watchlistarr-1  R...                                   0.0s 
Attaching to watchlistarr-1
watchlistarr-1  | 04:36:43.465 [io-compute-3] INFO  configuration.ConfigurationUtils$ - Successfully connected to Sonarr
watchlistarr-1  | 04:36:43.738 [io-compute-3] ERROR configuration.ConfigurationUtils$ - Unable to connect to Radarr at host.docker.internal:7878, with error java.net.ConnectException: Connection refused
watchlistarr-1  | java.lang.IllegalArgumentException: Unable to connect to Radarr at host.docker.internal:7878, with error java.net.ConnectException: Connection refused
watchlistarr-1  | 	at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:336)
watchlistarr-1  | 	at configuration.ConfigurationUtils$.$anonfun$getRadarrConfig$5(ConfigurationUtils.scala:176)
watchlistarr-1  | 	at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-1  | 	at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-1  | 	at map @ configuration.ConfigurationUtils$.$anonfun$getRadarrConfig$4(ConfigurationUtils.scala:170)
watchlistarr-1  | 	at flatMap @ configuration.ConfigurationUtils$.$anonfun$getRadarrConfig$4(ConfigurationUtils.scala:170)
watchlistarr-1  | 	at apply @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-1  | 	at fromFuture @ http.HttpClient.httpRequest(HttpClient.scala:41)
watchlistarr-1 exited with code 1`

This is my current compose setup 
`services: 
  watchlistarr: 
    image: nylonee/watchlistarr 
    environment: 
      SONARR_BASE_URL: http://192.168.1.231:8989
      RADARR_BASE_URL: http://192.168.1.231:7878
      SONARR_API_KEY: _removed_ 
      RADARR_API_KEY: _removed_
      PLEX_TOKEN: _removed_
    volumes: 
      - ./watchlistarr/:/config
    restart: unless-stopped`

If I run it without an existing directory in ./watchlistarr then I also get an added log that the config.yaml was created, however it only seems to make the directory and no config.yaml

**Comment by Redryan243** [comment]
I pulled the config manually and changed my base urls to http://radarr:7878 and http://sonarr:8989 and everything worked. It seems the issue is with the defaults not working and the config.yaml not pulling to the volume

**Comment by Redryan243** [comment]
And apparently the default turns on the deletesync. A ton of my media just got deleted,  and its in watchlistarrs logs. I'd definitely work on the default setup.

**Comment by Redryan243** [comment]
Upon further testing the config.yaml is not being read either. The volume is causing the directory to be created where I expect it, but no config was generated there, and it's not reading from my config that I manually saved there.

**Comment by KJ-Waller** [comment]
How did you end up getting this to work? I tried it by copying [this config template](https://github.com/nylonee/watchlistarr/blob/main/src/main/resources/config-template.yaml) into my ./watchlistarr as config.yaml, uncommented the baseUrl and apiKey an filled in http://radarr:7878 and http://sonarr:8989 like you said, but I still get the connection refused error.

```
  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_TOKEN=${PLEX_TOKEN}
      - SONARR_BASE_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_BASE_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - LOG_LEVEL=info
    volumes:
      - ./watchlistarr/:/config
    networks:
      - bridge
    depends_on:
      - plex
      - sonarr
      - radarr
    restart: unless-stopped
```

./watchlistarr/config.yaml
```
## Watchlistarr Configuration
## Uncomment the lines you would like to configure, then save this file and restart Watchlistarr

#interval:
## How often do you want Watchlistarr to pull the latest from Plex? In general, 10-30 seconds is okay.
## If you're running this on a slower system (e.g. Raspberry Pi), you may want to increase this
## Note: If you do not have Plex Pass, this will be overridden to ~19 minute syncs, see README
#  seconds: 10


#################################################################
## Sonarr Configuration
#################################################################

#sonarr:
## Base URL for Sonarr, including the 'http' and port and any configured urlbase. DEFAULT: "localhost:8989"
 baseUrl: "http://sonarr:8989"

## API key for Sonarr, found in your Sonarr UI -> General settings
 apikey: "<omitted>"

## If qualityProfile is not set, Watchlistarr will grab the first one it finds on Sonarr
#  qualityProfile: "Your Desired Sonarr Quality Profile"

## Root folder for Sonarr. If not set, will grab the first one it finds on Sonarr
#  rootFolder: "/root/folder/location"

## Boolean flag to bypass tv shows that are on the Sonarr Exclusion List. DEFAULT: false
#  bypassIgnored: false

## The monitoring option tells Sonarr what episodes to monitor. (e.g. last season only, all, etc.)
## All possible values are under 'MonitorTypes' in sonarr.tv/docs/api. DEFAULT: all
#  seasonMonitoring: all

## The tag to attach to the show when sending to Sonarr
#  tags:
#    - watchlistarr


#################################################################
## Radarr Configuration
#################################################################

#radarr:
## Base URL for Radarr, including the 'http' and port and any configured urlbase. DEFAULT: "localhost:7878"
 baseUrl: "http://radarr:7878"

## API key for Radarr, found in your Radarr UI -> General settings
 apikey: "<omitted>"

## If not set, will grab the first one it finds on Radarr
#  qualityProfile: "Your Desired Radarr Quality Profile"

## If not set, will grab the first one it finds on Radarr
#  rootFolder: "/root/folder/location"

## Boolean flag to bypass movies that are on the Radarr Exclusion List
#  bypassIgnored: false

## The tag to attach to the show when sending to Radarr
#  tags:
#    - watchlistarr


#################################################################
## Plex Configuration
#################################################################

#plex:
## Multiple tokens can be provided
#  token: "YOUR-PLEX-TOKEN"

## Don't sync friends watchlists, only your own. DEFAULT: false (e.g. sync everybody's watchlists)
#  skipfriendsync: false


#################################################################
## Delete Sync Configuration
#################################################################

## WARNING: This WILL delete your content off Sonarr/Radarr INCLUDING files if
#delete:
## If enabled, movies that are not watchlisted will be deleted from Radarr. DEFAULT: false
#  movie: false

## If enabled, shows that have no more planned seasons and are not watchlisted will be deleted from Sonarr. DEFAULT: false
#  endedShow: false

## If enabled, shows that still have planned seasons and are not watchlisted will be deleted from Sonarr. DEFAULT: false
#  continuingShow: false

## Number of days to wait before deleting content from the arrs (Deleting must be enabled). DEFAULT: 7
#  interval.days: 7

## Choose whether you want to delete the files as well, or only the entry in Sonarr/Radarr. DEFAULT: true
#  deleteFiles: true
```

I can confirm that any container part of the "bridge" network can reach radarr and sonarr using http://radarr:7878 and http://sonarr:8989.

**Comment by petercockroach** [comment]
I can't say if this is the problem for sure, but you need to uncomment #sonarr and #radarr

**Comment by andreypopov** [comment]
volumes:
      - ./watchlistarr/:/config
should it point to /app/config ?

**Comment by Redryan243** [comment]
No, I have it currently running with ./watchlistarr:/config
