### ISSUE TITLE
Unable to find quality profile

### ISSUE THREAD

**Issue by sacwooky** [nylonee/watchlistarr#90]
I have entered 1080p h265 Balanced in the Sonarr Quality Profile Variable which is the correct profile name for Sonarr.  As you can see below, it says Unable to find quality profile 1080p.  It states Possible values are List(QualityProfile(1080p h265 Balanced ,7), it seems this is a issue with the spacing.  I tried to use quotes " and it didn't work.  What format do I need to use to get Watchlistarr to see the correct profile?  Also, I'm using unraid docker and doesn't appear there is a appdata folder location.  Where can I find the config files?

java.lang.IllegalArgumentException: Unable to find quality profile 1080p. Possible values are List(QualityProfile(1080p h265 Balanced ,7), QualityProfile(1080p Optimal,8), QualityProfile(1080p Transparent (Double Grab),9), QualityProfile(1080p Balanced,10), QualityProfile(1080p h265 Balanced (Single Grab),11), QualityProfile(1080p Balanced (Single Grab),12), QualityProfile(1080p Optimal (Single Grab),13), QualityProfile(1080p Transparent (Single Grab),14), QualityProfile(1080p Transparent,15))
        at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:233)
        at configuration.ConfigurationUtils$.$anonfun$getQualityProfileId$3(ConfigurationUtils.scala:149)
        at scala.Option.getOrElse(Option.scala:201)
        at configuration.ConfigurationUtils$.getQualityProfileId(ConfigurationUtils.scala:149)
        at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$8(ConfigurationUtils.scala:93)
        at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$8$adapted(ConfigurationUtils.scala:89)
        at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:370)
        at as @ Server$.$anonfun$run$1(Server.scala:31)
        at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:370)
        at as @ Server$.$anonfun$run$1(Server.scala:31)
        at void @ org.typelevel.keypool.KeyPool$.reap(KeyPool.scala:187)
        at main$ @ Server$.main(Server.scala:11)
        at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
        at >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:370)
        at as @ Server$.$anonfun$run$1(Server.scala:31)
13:56:23.708 [io-compute-5] INFO  configuration.ConfigurationUtils$ - Successfully connected to Sonarr
13:56:23.755 [io-compute-1] ERROR configuration.ConfigurationUtils$ - Unable to find quality profile 1080p. Possible values are List(QualityProfile(1080p h265 Balanced ,7), QualityProfile(1080p Optimal,8), QualityProfile(1080p Transparent (Double Grab),9), QualityProfile(1080p Balanced,10), QualityProfile(1080p h265 Balanced (Single Grab),11), QualityProfile(1080p Balanced (Single Grab),12), QualityProfile(1080p Optimal (Single Grab),13), QualityProfile(1080p Transparent (Single Grab),14), QualityProfile(1080p Transparent,15))

**Comment by nylonee** [comment]
It does indeed look like a spacing issue! I'll try this on unraid and see if I can replicate the issue.

There isn't an appdata folder because there isn't any additional configuration/storage needed once the initial docker env variables are configured.

**Comment by nylonee** [comment]
I've got a fix, will merge it in soon, thanks again for raising this!

**Comment by nylonee** [comment]
This will be on the `beta` tag on docker, feel free to use that in your unraid setup (by setting your repository to `nylonee/watchlistarr:beta`. After some testing I'll make a release

**Comment by sacwooky** [comment]
Thanks!  I just tested it out and no errors!  Thanks again!
